pueblos/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic import TemplateView

from . import views

app_name = 'pueblos'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<noticia_200_id>[0-9]+)/noticia200/$', views.noticia200, name='noticia200'),
    url(r'^(?P<noticia_200_id>[0-9]+)/delete_words/$', views.delete_words, name='delete_words'),
    url(r'^listaNoticias200/$', views.ListaNoticias200View.as_view(), name='listaNoticias200'),
    url(r'^(?P<noticia_id>[0-9]+)/show_notice_categories/$', views.show_notice_categories,
        name='show_notice_categories'),
    url(r'^noticesContext/$', views.notices_context_view, name='notices_context'),
    # url(r'^noticesContextStep/$', views.NoticesContextStepView, name='notices_context_step'),
    url(r'^noticesContextStep/$', TemplateView.as_view(template_name="pueblos/noticesContextStep.html"),
        name='notices_context_step'),
    url(r'^set_context_options_run/$', views.set_context_options_run, name='set_context_options_run'),
    # url(r'^processWord/setIndividualContext/$', views.context_options_process, name='context_options_process'),
    url(r'(?P<option>[a-zA-Z]+)/setIndividualContext/$', views.context_options_router, name='context_options_router'),
    url(r'(?P<page>[0-9]+)/syntactic_dictionary/(?P<filter>\w+)$', views.syntactic_dictionary,
        name='syntactic_dictionary'),
    url(r'^search_word/$', views.search_word, name="search_word"),
    url(r'^save_word/$', views.save_word, name="save_word"),
    url(r'^noticeSuggestTags/$', views.notice_suggest_tags, name='notice_suggest_tags'),
    url(r'^(?P<test_case_id>[0-9]+)/checkStatus/$', views.check_status, name='check_status'),
    url(r'^singularize/$', views.singularize, name='singularize'),
    # url(r'^test_task/$', views.test_task_view, name='test_task'),
    ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

tfmsemandal/urls.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
"""tfmsemandal URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^pueblos/', include('pueblos.urls', namespace="pueblos")),
    url(r'^admin/', admin.site.urls),
]

pueblos/forms.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
from django import forms
from django.core.validators import MinLengthValidator

value_error1000 = 'El valor tiene que estar entre 1 y 1000'
value_error40 = 'El valor tiene que estar entre 1 y 40'
value_error100 = 'El valor tiene que estar entre 1 y 100'
required = 'Este campo es requerido'

default_errors100 = {
        'required': required,
        'invalid': value_error100
    }
default_errors1000 = {
    'required': required,
    'invalid': value_error1000
}

default_errors40 = {
    'required': required,
    'invalid': value_error40
}


class ContextOptionsForm1(forms.Form):
    delete = forms.BooleanField(required=False, label='Eliminar noticias')
    numberOfNotices = forms.IntegerField(required=False, min_value=1, max_value=1000, error_messages=default_errors1000,
                                         label='Nº de Noticias (Máx. 1000) - Se ejecuta si se eliminan las noticias')


class ContextOptionsForm2(forms.Form):
    use_syn_dict = forms.BooleanField(required=False, label='¿Usar diccionario sintáctico?')


class ContextOptionsForm3(forms.Form):
    """
    percentage = forms.IntegerField(required=True, min_value=1, max_value=100, error_messages=default_errors100,
                                    label='Porcentaje de palabras por categoría')
    """
    limit = forms.IntegerField(required=True, min_value=1, max_value=1000, error_messages=default_errors1000,
                               label='Límite de palabras por categoría')


class ContextOptionsForm4(forms.Form):
    testNotices = forms.IntegerField(required=True, min_value=1, max_value=1000, error_messages=default_errors1000,
                                     label='Número de noticias de test - Máx. 1000')


class ContextOptionsForm(forms.Form):
    n_notices = forms.IntegerField(required=False, min_value=1, max_value=1000, error_messages=default_errors1000,
                        label='Número de noticias de entrenamiento (Max 1000)')
    n_notices_test = forms.IntegerField(required=True, min_value=1, max_value=1000, error_messages=default_errors1000,
                                        label='Numero de noticias de test (Max 1000)')
    limit = forms.IntegerField(required=True, min_value=1, max_value=40, error_messages=default_errors100,
                               label='Limite de palabras por categoria (Max 40)')
    confidence = forms.IntegerField(required=True, min_value=1, max_value=100, error_messages=default_errors100,
                                    label='Porcentaje de confianza que tiene que cumplir la regla')
    support = forms.IntegerField(required=True, min_value=1, max_value=100, error_messages=default_errors100,
                                 label='Porcentaje noticias que tiene que cumplir la regla (soporte)')
    use_syn_dict = forms.BooleanField(required=False, label='Usar diccionario sintáctico')


class GetTagForNoticeText(forms.Form):
    notice_body = forms.CharField(required=True, error_messages={'required': 'Por favor inserte algún texto'},
                                  validators=[MinLengthValidator(50, 'El texto debe tener al menos 50 caracteres')],
                                  label='Texto de la noticia', widget=forms.Textarea(attrs={'class': 'col-xs-9'}))

pueblos/views.py
#!/usr/bin/python
# -*- coding: utf-8 -*-
import json
import time
from StringIO import StringIO

from django.core.management import call_command
from django.http import Http404, HttpResponse
from django.shortcuts import get_object_or_404, render, redirect
from django.views import generic
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .forms import ContextOptionsForm, ContextOptionsForm1, ContextOptionsForm2, ContextOptionsForm3, \
    ContextOptionsForm4, GetTagForNoticeText
from .models import PueblosNoticias, PueblosNoticias200, PueblosNoticiasPalabras, PueblosPalabrasEliminar, \
    PueblosNoticiaCategorizada, PueblosCategoriasSemandal, PueblosDiccionarioSintactico, PueblosTestCase


class IndexView(generic.ListView):
    template_name = 'pueblos/index.html'
    # context_object_name = 'last_notices_list'

    def get_queryset(self):
        return
        # Return the last five published questions.
        # return PueblosNoticias.objects.order_by('fecha_ins')[:5]
        # return PueblosNoticias200.objects.all()[:5]


class DetailView(generic.DetailView):
    model = PueblosNoticias
    template_name = 'pueblos/detail.html'


class ListaNoticias200View(generic.ListView):
    template_name = 'pueblos/listaNoticias200.html'
    context_object_name = 'lista_noticias_200'

    def get_queryset(self):
        return PueblosNoticias200.objects.all()


def noticia200(request, noticia_200_id):
    noticia = get_object_or_404(PueblosNoticias200, pk=noticia_200_id)
    try:
        lista_palabras = PueblosNoticiasPalabras.objects.filter(noticia_200=noticia.id)
        categorias = noticia.get_categorias_string()
    except PueblosNoticiasPalabras.DoesNotExist:
        raise Http404("No hay palabras para esta noticia.")
    return render(request, 'pueblos/noticia200.html', {'noticia': noticia,
    'lista_palabras': lista_palabras, 'categorias': categorias})


def delete_words(request, noticia_200_id):
    # notice = get_object_or_404(PueblosNoticias200, pk=noticia_200_id)
    words = request.POST.getlist('words[]')
    filename = './pueblos/docs/lista_palabras_eliminar.txt'
    with open(filename, 'a') as writer:
        for word in words:
            if 'delete' in request.POST:
                PueblosNoticiasPalabras.objects.filter(palabra=word).delete()
                # Almacenar la palabra en la base de datos de palabras a ignorar y al fichero de carga
                p = PueblosPalabrasEliminar.objects.filter(palabra=word)
                if not p.exists():
                    delete_word = PueblosPalabrasEliminar(palabra=word)
                    delete_word.save()
                    word = word.encode('utf-8')
                    writer.write(word + '\n')
            else:
                PueblosNoticiasPalabras.objects.get(noticia_200=noticia_200_id, palabra=word).delete()
    # return HttpResponseRedirect(reverse('pueblos:listaNoticias200'))
    return redirect('pueblos:noticia200', noticia_200_id=noticia_200_id)


def show_notice_categories(request, noticia_id):
    notices = PueblosNoticiaCategorizada.objects.filter(noticia=noticia_id)
    if len(notices) == 0:
        return render(request, 'pueblos/show_notice_categories.html', {'notice': None})
    suggested_categories = []

    if len(notices) > 0:
        this_notice = get_object_or_404(PueblosNoticias, pk=noticia_id)
        categories = this_notice.get_categorias_string()
        for notice in notices:
            if notice.categorias_sugeridas_id:
                cat = PueblosCategoriasSemandal.objects.get(id=notice.categorias_sugeridas_id)
                suggested_categories.append(cat.dscategoria)

    return render(request, 'pueblos/show_notice_categories.html', {'notice': this_notice, 'categories': categories,
                                                                   'suggested_categories': suggested_categories})

# ---------------------------- Context ----------------------------#

"""
class NoticesContextView(TemplateView):
    template_name = 'pueblos/noticesContextOptions.html'
    form_class = ContextOptionsForm

    def dispatch(self, request, *args, **kwargs):
        return super(NoticesContextView, self).dispatch(request, *args, **kwargs)
"""


def check_status(request, test_case_id):
    test_case = get_object_or_404(PueblosTestCase, pk=test_case_id)
    state = test_case.state
    return render(request, 'pueblos/checkStatus.html', {'state': state})


def notice_suggest_tags(request):
    form = GetTagForNoticeText()
    suggested_tags = None
    if request.method == 'POST':
        form = GetTagForNoticeText(request.POST)
        if form.is_valid():
            clean_data = form.cleaned_data
            suggested_tags = recommend_tags(request, clean_data['notice_body'])
            print 'suggested_tags ' + suggested_tags
    return render(request, 'pueblos/noticeSuggestTags.html', {'form': form, 'suggested_tags': suggested_tags})


def recommend_tags(request, notice_body, use_syn_dict):
    print 'recommend_tags, use dict ' + str(use_syn_dict)
    errbuf = StringIO()
    suggested_categories = StringIO()
    call_command('recommend_tags', notice_body=notice_body, use_syn_dict=use_syn_dict, stdout=suggested_categories,
                 stderr=errbuf)
    tags = suggested_categories.getvalue()
    if len(tags) < 3:
        tags = 'No se encuentra una categoría adecuada'
    return tags


def notices_context_view(request):
    data = {}
    if request.method == 'POST':
        form = ContextOptionsForm(request.POST)
        if form.is_valid():
            time.sleep(10)
            # request.session['cleaned_data'] = form.cleaned_data
            clean = form.cleaned_data
            data['stat'] = 'ok'
            confidence = clean['confidence'] / 100.0
            support = clean['support'] / 100.0
            if clean['limit'] > 40:
                limit = 40
            else:
                limit = clean['limit']
            test_case = PueblosTestCase(n_notices=clean['n_notices'], n_notices_test=clean['n_notices_test'],
                                        limit=limit, use_syn_dict=clean['use_syn_dict'],
                                        confidence=confidence, support=support)
            test_case.save()
            messages = ['Datos recogidos en el servidor',
                        'Numero de noticias de entrenamiento: ' + str(clean['n_notices']),
                        'Número de Noticias de test: ' + str(clean['n_notices_test']),
                        'Límite de palabras por categoría: ' + str(limit),
                        'Confianza ' + str(clean['confidence']), 'Soporte ' + str(clean['support']),
                        'Usar diccionario sintáctico: ' + str(clean['use_syn_dict'])]
            data['message'] = messages
            data['test_link'] = '/pueblos/' + str(test_case.id) + '/checkStatus'
            return HttpResponse(json.dumps(data), content_type="application/json")
        # return set_context_options_run(request)
        else:
            data['stat'] = 'error'
            return render(request, 'pueblos/noticesContextOptions.html', {'form': form})
    else:
        form = ContextOptionsForm()
        return render(request, 'pueblos/noticesContextOptions.html', {'form': form})


def set_context_options_run(request):
    cleaned_data = request.session.get('cleaned_data')
    if cleaned_data:
        if cleaned_data['numberOfNotices'] is None:
            cleaned_data['numberOfNotices'] = 10
        return render(request, 'pueblos/setContextOptionsAndRun.html', {'cleaned_data': cleaned_data})
    else:
        return redirect('pueblos:noticesContextView')


def context_options_router(request, option):
    print 'context_options_router option ' + option
    form = None
    action_url = 'pueblos/' + option + '/setIndividualContext/'
    if option == 'cleanDB':
        if request.method == 'POST':
            form = ContextOptionsForm1(request.POST)
            if form.is_valid():
                clean_data = form.cleaned_data
                return clean_db(request, clean_data['delete'], clean_data['numberOfNotices'])
        else:
            form = ContextOptionsForm1()

    elif option == 'processWord':
        form = ContextOptionsForm2()
        if request.method == 'POST':
            form = ContextOptionsForm2(request.POST)
            if form.is_valid():
                clean_data = form.cleaned_data
                return process_word_list(request, clean_data['use_syn_dict'])
    elif option == 'generateContext':
        form = ContextOptionsForm3()
        if request.method == 'POST':
            form = ContextOptionsForm3(request.POST)
            if form.is_valid():
                clean_data = form.cleaned_data
                # return generate_context(request, clean_data['percentage'], clean_data['limit'])
                return generate_context(request, clean_data['limit'])
    elif option == 'getRandomNotices':
        form = ContextOptionsForm4()
        if request.method == 'POST':
            form = ContextOptionsForm4(request.POST)
            if form.is_valid():
                clean_data = form.cleaned_data
                return get_random_notices(request, clean_data['testNotices'])
    if form:
        errors = form.errors
        print form.errors
    return render(request, 'pueblos/setIndividualContext.html', {'form': form, 'action_url': action_url})


def context_options_process(request):
    # print 'context_options_process'
    action_url = 'pueblos/processWord/setIndividualContext/'
    if request.is_ajax():
        return process_word_list(request)
    return render(request, 'pueblos/setIndividualContext.html', {'action_url': action_url})

"""
Diccionary
"""


def syntactic_dictionary(request, page='1', filter='empty'):
    MAX_ITEMS_FOR_PAGE = 50
    saved = False
    if filter == 'plural':
        dictionary_list = PueblosDiccionarioSintactico.objects.filter(word__endswith='s').order_by('word')
    else:

pueblos/templates/pueblos/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <title>Semandal</title>
        <!-- Latest compiled and minified CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
        <!-- Optional theme -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{%  static "pueblos/css/djangoStyle.css" %}" />
        <!--link rel="stylesheet" href="{% static 'pueblos/css/.css' %}"-->
        <!-- Libraries -->
        <script type="text/javascript" src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    </head>
    <body>
        <div class="page-header">
            <h1><a href="{% url 'pueblos:index' %}">Semandal</a></h1>
        </div>

        <div class="container col-xs-12 col-xs-offset-1">
            <div class="row">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </body>
</html>

pueblos/templates/pueblos/checkStatus.html
{% extends 'pueblos/base.html' %}

{% block content %}
    <h1>El estado del caso de uso es: {{ state }} </h1>
    <br />
    <a href="{% url 'pueblos:index' %}">Volver al inicio</a>
{% endblock content %}

pueblos/templates/pueblos/index.html
{% extends 'pueblos/base.html' %}

{% block content %}
<ul>
    <li>
        <a href="{% url 'pueblos:listaNoticias200' %}">Listado de noticias de entrenamiento</a>
    </li>
    <li>
        <a href="{% url 'pueblos:notices_context_step' %}">Administrar noticias entrenamiento y contexto</a>
    </li>
    <li>
        <a href="{% url 'pueblos:notices_context' %}">Generar caso de estudio</a>
    </li>
    <li>
        <a href="{% url 'pueblos:notice_suggest_tags' %}">Sugerir etiquetas para noticia</a>
    </li>
    <li>
        <a href="{% url 'pueblos:syntactic_dictionary' 1 None %}">Diccionario sintáctico</a>
    </li>
    <li>
        <a href="{% url 'pueblos:syntactic_dictionary' 1 'plural' %}">Diccionario sintáctico solo para plurales</a>
    </li>
</ul>
{% endblock content %}

pueblos/templates/pueblos/noticeSuggestTags.html
{% extends 'pueblos/base.html' %}
{% load staticfiles %}
{% block content %}
<h3 class="align-left">Sugerir etiquetas a una noticia</h3>
<hr>
<form action="{% url 'pueblos:notice_suggest_tags' %}" method="post">
    {% csrf_token %}
    <div class="form-group col-xs-12">
        <label for="{{ form.notice_body.name }}">{{ form.notice_body.label }}:</label><br>
        {{ form.notice_body }}
    </div>
    {% if form.errors %}
        {% for field in form %}
            {% for error in field.errors %}
                <div class="alert alert-danger">
                    <strong>{{ error|escape }}</strong>
                </div>
            {% endfor %}
        {% endfor %}
        {% for error in form.non_field_errors %}
            <div class="alert alert-danger">
                <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endif %}
    {% if suggested_tags %}
        <div class="form-group">
            {{ suggested_tags }}
        </div>
    {% endif %}
    <input type="submit" value="Sugerir">
</form>

<br />
<br />
<a href="{% url 'pueblos:index' %}">Volver atrás</a>
{% endblock content %}

pueblos/templates/pueblos/noticesContextOptions.html
{% extends 'pueblos/base.html' %}
{% load staticfiles %}
{% block content %}
<h3 class="align-left">En esta sección podrá crear casos de estudio para su posterior revisión</h3>
<hr>
<form action="{% url 'pueblos:notices_context' %}" method="post">
    {% csrf_token %}
    {{form.as_p}}
    <div class="ajaxProgress">
        <h3>Por favor espere... Esta tarea puede tardar varios segundos</h3>
        <img src="{%  static "pueblos/img/ajax-loader.gif" %}">
    </div>
    <a href="javascript:FireCall()" class="setOptionsAndSubmit btn btn-success">Ejecutar</a>
</form>
<div id="error">Hay algún error con la petición, revise que los datos sean los correctos</div>
<div id="output"></div>

<br />
<br />
<a href="{% url 'pueblos:index' %}">Volver atrás</a>
    <script type="text/javascript" src="{%  static "pueblos/js/noticesContextOptions.js" %}"></script>
{% endblock content %}

pueblos/templates/pueblos/noticesContextStep.html
{% extends 'pueblos/base.html' %}

{% block content %}
    <ul>
        <li><a href="/pueblos/cleanDB/setIndividualContext">Limpiar BD</a></li>
        <li><a href="/pueblos/processWord/setIndividualContext">Procesar palabras de noticias</a></li>
        <li><a href="/pueblos/generateContext/setIndividualContext">Generar contexto</a></li>
        <li><a href="/pueblos/getRandomNotices/setIndividualContext">Generar lista de noticias con categorías</a></li>
    </ul>
    <a href="{% url 'pueblos:index' %}">Volver atrás</a>
{% endblock content %}

pueblos/templates/pueblos/noticia200.html
{% extends 'pueblos/base.html' %}

{% block content %}
    <h1>{{ noticia.dstitular }}</h1>

    {{ noticia.dscuerpo }}

    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <div class="col-md-12">
        <div class="container">
            <h3>Esta noticia tiene las siguientes categorías:</h3>
        {% for categoria in categorias %}
            <p class="lead">{{categoria}}</p>
        {% endfor %}
        </div>
        <hr>
    </div>

    <form action="{% url 'pueblos:delete_words' noticia.id %}" method="post">
    {% csrf_token %}

    {% for palabra in lista_palabras %}
        <div class="form-group">
            <label>
                <input type="checkbox" name="words[]" value="{{ palabra.palabra }}" />
                {{ palabra.palabra }}
            </label>
        </div>
    {% endfor %}
    <br />
    <input type="checkbox" name="delete" value="delete" />
        ¿Añadir a lista de exclusiones? Las palabras no aparecerán para ninguna categoría<br />

    <input type="submit" value="Eliminar" />
    </form>

    <br />
    <br />
    <a href="{{request.META.HTTP_REFERER}}">Volver atrás</a>
{% endblock content %}

pueblos/templates/pueblos/setContextOptionsAndRun.html
{% extends 'pueblos/base.html' %}

{% block content %}
    <h3>Parámetros ejecutados</h3>
    {% if cleaned_data %}
        {% for field,value in cleaned_data.items %}
            <p>{{field}}: {{value}}</p>
        {% endfor %}
    {% endif %}
    <br />
    <br />
    <a href="{{request.META.HTTP_REFERER}}">Volver atrás</a>
    <a href="{% url 'pueblos:index' %}}">Volver al índice</a>
{% endblock content %}

pueblos/templates/pueblos/syntactic_dictionary.html
{% extends 'pueblos/base.html' %}
{% load staticfiles %}
{% block content %}
    {% if filter == 'plural' %}
        <h1 class="col-xs-11">Diccionario sintáctico - Palabras terminadas en s</h1>
    {% else %}
        <h1 class="col-xs-9">Diccionario sintáctico</h1>
    {% endif %}
    <hr>
    <h4 class="col-xs-9">Buscar palabra</h4>
    <form id="search_word_form" class="userinput form-horizontal" role="form" method="POST"
          action="{% url 'pueblos:search_word' %}">
        {% csrf_token %}
        <div class="form-group">
			<label class="col-xs-4 control-label">Palabra a buscar: </label>
			<div class="col-xs-4">
				<input type="text" class="form-control" name="search_word" value="">
			</div>
		</div>
        <div class="form-group">
			<div class="col-xs-8 text-right"> <br />
                <input type="submit" class="btn btn-info" value="Buscar">
			</div>
		</div>
    </form>
    <form id="save_word_form" class="userinput form-horizontal" hidden="hidden" role="form" method="POST"
          action="{% url 'pueblos:save_word' %}">
        {% csrf_token %}
        <input type="hidden" name="found_word" value="">
        <h4 class="col-xs-9">Palabra encontrada</h4>
        <div class="form-group">
			<label class="col-xs-4 control-label"> </label>
			<div class="col-xs-4">
				<input type="text" class="form-control" name="replace_word" value="">
			</div>
		</div>
        <label class="col-xs-4 control-label">¿Borrar palabra?</label>
        <div class="col-xs-1">
            <input type="checkbox" name="delete_word" value="">
        </div>
        <div class="form-group">
			<div class="col-xs-8 text-right"> <br />
                <input type="submit" class="btn btn-info" value="Modificar">
			</div>
		</div>
    </form>
    <span class="label col-xs-offset-4" hidden="hidden" id="message"></span>
    {% if words %}
        </br>
        </br>
        <div class="pagination">
            <span class="step-links">
                {% if words.has_previous %}
                    <a href="{% url 'pueblos:syntactic_dictionary' words.previous_page_number filter %}">Anterior</a>
                {% endif %}

                <span class="current">
                    Página {{ words.number }} de {{ words.paginator.num_pages }}.
                </span>

                {% if words.has_next %}
                    <a href="{% url 'pueblos:syntactic_dictionary' words.next_page_number filter %}">Siguiente</a>
                {% endif %}
            </span>
        </div>
        <div>
            Palabras del diccionario:
            <form id="myform" action="{% url 'pueblos:syntactic_dictionary' words.number filter %}" method="post">
                {% csrf_token %}
                <table class="table table-striped table-bordered">
                    <thead><tr><th>Borrar</th><th>Palabra a sustituir</th><th>Palabra nueva</th></tr></thead>
                    <tbody>
                {% for word in words %}
                    {% if word.replace_word %}
                        <tr class="info">
                    {% else %}
                        <tr>
                    {% endif %}
                        <td>
                            <input type="checkbox" name="del_words[]" value="{{ word.word }}" />
                        </td>
                        <td>
                            {{ word.word }}
                        </td>
                        <td>
                            <input type="text" name="{{ word.word }}" value="{{ word.replace_word }}" />
                        </td>
                    </tr>
                {% endfor %}
                    </tbody>
                </table>
                <button type="submit" class="btn btn-info">Ejecutar</button>
            </form>
            <div class="error"></div>
            <div class="ajaxProgress">
                <h3>Por favor espere... Esta tarea puede tardar varios minutos</h3>
                <img src="{%  static 'pueblos/img/ajax-loader.gif' %}">
            </div>

            <div id="output"></div>
        </div>
    {% else %}
        <p>
            El diccionario está vacío, por favor seleccione unas noticias
            <a href="{% url 'pueblos:notices_context_step' %}">aquí </a> y genere sus palabras asociadas.
        </p>
    {% endif %}
    {% if saved %}
        <div class="success">Datos guardados en la base de datos</div>
    {% endif %}
    <br />
    <br />
    <a href="{% url 'pueblos:index' %}">Volver a la página principal</a> </br>
    <div class="pagination">
        <span class="step-links">
            {% if words.has_previous %}
                <a href="{% url 'pueblos:syntactic_dictionary' words.previous_page_number filter %}">Anterior</a>
            {% endif %}

            <span class="current">
                Página {{ words.number }} de {{ words.paginator.num_pages }}.
            </span>

            {% if words.has_next %}
                <a href="{% url 'pueblos:syntactic_dictionary' words.next_page_number filter %}">Siguiente</a>
            {% endif %}
        </span>
    </div>
    <script type="text/javascript" src="{%  static 'pueblos/js/syntactic_dictionary.js' %}"></script>
{% endblock content %}